// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ypkcviedfxpfgcsxrjhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwa2N2aWVkZnhwZmdjc3hyamhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3Nzc3OTEsImV4cCI6MjA3ODM1Mzc5MX0.7d1oAdIX8XIGXnlIq2oqofZURpGId-rPgmExRws9bxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);